- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    port: 22
    script: |
      cd /home/ec2-user/5-dollar-gift
      git pull --rebase origin main
      /usr/bin/python3.12 -m pip install --user -r requirements.txt

      oldpid=$(lsof -ti:5000)
      if [ -n "$oldpid" ]; then
        kill -9 $oldpid
      fi

      nohup /usr/bin/python3.12 five_dollar_app.py > app.log 2>&1 < /dev/null &